----deployment file-------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin #1
spec:
  selector:
    matchLabels:
      app: phpmyadmin #2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: phpmyadmin #4
    spec:
      containers:
      - name: phpmyadmin #5
        image: phpmyadmin #\\ Image name
        ports:
        - containerPort: 80 #port number 
        
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: phpmyadmin #1 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
